[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.1.2",
    "openai>=1.51.0",
    "pandas>=2.2.3",
    "requests>=2.32.3",
    "torch>=2.4.1",
    "tqdm>=4.66.5",
    "transformers>=4.45.1",
]
